services:
  api:
    build: ./backend
    restart: unless-stopped
    env_file: ./backend/.env
    ports:
      - "10.8.97.14:8081:5432"
    depends_on:
      - db
    #networks:
    #- web-app-network
    
    #develop:
      #watch:
        #- action: sync
          #path: ./backend
          #target: /TaBProject_backend
  web:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "10.8.97.14:8080:5173"
    depends_on:
      - api
    #networks:
    #- web-app-network

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: monogo-db
    volumes:
      - 

#networks:
  #web-app-network:
   # driver: bridge
    #develop:
      #watch:
        #- action: sync
         # path: ./frontend
          #target: /TaBProject_frontend