services:
  db:
    build: ./backend
    ports:
      - "25432:5432"
    #develop:
      #watch:
        #- action: sync
          #path: ./backend
          #target: /TaBProject_backend
  web:
    build: ./frontend
    ports:
      - "8080:5173"
    #develop:
      #watch:
        #- action: sync
         # path: ./frontend
          #target: /TaBProject_frontend