services:
  db:
    build: ./backend
    env_file: ./backend/.env
    ports:
      - "25432:5432"
    #networks:
    #- web-app-network
    
    #develop:
      #watch:
        #- action: sync
          #path: ./backend
          #target: /TaBProject_backend
  web:
    build: ./frontend
    ports:
      - "8080:5173"
    depends_on:
      - db
    #networks:
    #- web-app-network

#networks:
  #web-app-network:
   # driver: bridge
    #develop:
      #watch:
        #- action: sync
         # path: ./frontend
          #target: /TaBProject_frontend